Fix FluenceJS changelog
fluencelabs/docs pull request #5
Opened 2022-11-01 01:08 UTC by coder11

2022-11-01 08:54 UTC, shamsartem requested changes
Please fix or remove the links

2022-11-01 08:54 UTC, shamsartem commented on docs/build/fluence-js/changelog.md
> +## [0.26.3](https://github.com/fluencelabs/fluence-js/releases/tag/0.26.3) - Oct 26, 2022
These links are unreachable:

https://github.com/fluencelabs/fluence-js/releases/tag/0.26.3
https://github.com/fluencelabs/fluence-js/releases/tag/0.24.0
https://github.com/fluencelabs/fluence-js/releases/tag/0.24.1
https://github.com/fluencelabs/fluence-js/releases/tag/0.26.2
https://github.com/fluencelabs/fluence-js/releases/tag/0.26.0
https://github.com/fluencelabs/fluence-js/releases/tag/0.25.2
https://github.com/fluencelabs/fluence-js/releases/tag/0.23.7
https://github.com/fluencelabs/fluence-js/releases/tag/0.23.8
https://github.com/fluencelabs/fluence-js/releases/tag/0.23.2
https://github.com/fluencelabs/fluence-js/releases/tag/0.23.6
https://github.com/fluencelabs/fluence-js/releases/tag/0.23.4
https://github.com/fluencelabs/fluence-js/releases/tag/0.23.5
https://github.com/fluencelabs/fluence-js/releases/tag/0.21.7
https://github.com/fluencelabs/fluence-js/releases/tag/0.22.0
https://github.com/fluencelabs/fluence-js/releases/tag/0.23.0
https://github.com/fluencelabs/fluence-js/releases/tag/0.21.8
https://github.com/fluencelabs/fluence-js/releases/tag/0.25.1
https://github.com/fluencelabs/fluence-js/releases/tag/0.26.1
https://github.com/fluencelabs/fluence-js/releases/tag/0.23.1
https://github.com/fluencelabs/fluence-js/releases/tag/0.21.4
https://github.com/fluencelabs/fluence-js/releases/tag/0.21.6

2022-11-01 08:54 UTC, shamsartem commented on docs/build/fluence-js/changelog.md
> +Add v4 version of compiler support. It makes possible to use any name for functions and data structures in aqua without colliding with variable names in FluenceJS ([#190](https://github.com/fluencela
Add v4 of compiler support. It makes it possible to use any name for functions and data structures in aqua without collisions with variable names in FluenceJS

2022-11-01 09:27 UTC, folex commented on docs/build/fluence-js/changelog.md
> +## [0.26.3](https://github.com/fluencelabs/fluence-js/releases/tag/0.26.3) - Oct 26, 2022
They all miss `v` before version

2022-11-02 15:01 UTC, shamsartem approved these changes
Cool thanks

2022-11-02 15:13 UTC, folex approved these changes

2022-11-02 16:06 UTC, merged